version: "3.1"

services:
  mongo:
    image: mongo:4
    restart: unless-stopped
    volumes:
      - ./db:/data/db

  bot:
    build: .
    restart: unless-stopped
    command: yarn start
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      ARYION_BOT_PREFIX: ${ARYION_BOT_PREFIX}
      ARYION_BOT_INTERVAL: ${ARYION_BOT_INTERVAL}
      MONGODB_URL: mongodb://mongo:27017/aryionbot
      DEBUG: aryionbot
