version: '3.1'

services:
  mongo:
    image: mongo:4.2.6
    restart: always
    volumes:
      - ./db:/data/db

  bot:
    build: .
    restart: always
    command: yarn dev
    volumes:
      - ./src:/usr/local/app/src
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      MONGODB_URL: mongodb://mongo:27017/aryionbot
      DEBUG: aryionbot
